"use client";

import Link from "next/link";
import { useLanguage } from "@/components/LanguageProvider";

interface FooterProps {
  lang: string;
}

export default function Footer({ lang }: FooterProps) {
  const { t } = useLanguage();
  const isZh = lang === 'zh';
  
  return (
    <footer className="bg-gray-50 border-t border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* 品牌信息 */}
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-2xl">📚</span>
              <span className="text-xl font-bold text-gray-900">
                {t('common.appName')}
              </span>
            </div>
            <p className="text-gray-600 mb-4">
              {t('footer.brandDesc1')}<br />
              {t('footer.brandDesc2')}
            </p>
            <p className="text-sm text-gray-400">
              {t('footer.copyright')}
            </p>
            
            {/* 英文版额外的合规声明 */}
            {!isZh && (
              <div className="mt-4 p-3 bg-yellow-50 rounded-lg border border-yellow-200">
                <p className="text-xs text-yellow-800">
                  <strong>⚠️ AI Content Disclaimer:</strong> All stories and illustrations on this platform are generated by artificial intelligence and are intended for entertainment purposes only. They do not represent real events, people, or opinions.
                </p>
              </div>
            )}
          </div>
          
          {/* 快速链接 */}
          <div>
            <h3 className="font-semibold text-gray-900 mb-4">{t('footer.quickLinks')}</h3>
            <ul className="space-y-2 text-gray-600">
              <li>
                <Link href={`/${lang}/create`} className="hover:text-primary-orange transition-colors">
                  {t('common.startCreating')}
                </Link>
              </li>
              <li>
                <Link href={`/${lang}/pricing`} className="hover:text-primary-orange transition-colors">
                  {t('footer.pricing')}
                </Link>
              </li>
              <li>
                <Link href={`/${lang}/privacy`} className="hover:text-primary-orange transition-colors">
                  {t('footer.privacy')}
                </Link>
              </li>
              <li>
                <Link href={`/${lang}/terms`} className="hover:text-primary-orange transition-colors">
                  {t('footer.terms')}
                </Link>
              </li>
            </ul>
          </div>
          
          {/* 联系方式 */}
          <div>
            <h3 className="font-semibold text-gray-900 mb-4">{t('footer.contact')}</h3>
            <ul className="space-y-2 text-gray-600">
              <li className="flex items-center gap-2">
                <span>📧</span>
                <a href="mailto:haimozhouqiu@outlook.com" className="hover:text-primary-orange transition-colors">
                  haimozhouqiu@outlook.com
                </a>
              </li>
              <li className="flex items-center gap-2">
                <span>💬</span>
                <span>{t('footer.wechat')}</span>
              </li>
            </ul>
            
            {/* 英文版额外的合规链接 */}
            {!isZh && (
              <div className="mt-4 space-y-2">
                <a href={`/${lang}/privacy#coppa`} className="block text-xs text-blue-600 hover:underline">
                  🛡️ COPPA Compliant
                </a>
                <a href={`/${lang}/privacy#gdpr`} className="block text-xs text-blue-600 hover:underline">
                  🛡️ GDPR Compliant
                </a>
                <a href={`/${lang}/privacy#privacy-rights`} className="block text-xs text-blue-600 hover:underline">
                  🔒 Do Not Sell My Information
                </a>
              </div>
            )}
          </div>
        </div>
        
        {/* 底部声明 */}
        <div className="mt-8 pt-8 border-t border-gray-200">
          <p className="text-sm text-gray-500 text-center">
            {isZh 
              ? '本网站所有AI生成内容仅供娱乐参考，不代表任何真实事件或观点。'
              : '⚠️ AI-Generated Content Disclaimer: All stories and illustrations on this platform are generated by artificial intelligence and are intended for entertainment purposes only. They do not represent real events, people, or opinions. AI-generated content may contain inaccuracies. Parental review is recommended before sharing with children.'
            }
          </p>
        </div>
      </div>
    </footer>
  );
}
